import React, { Component } from 'react';
import {Helmet} from 'react-helmet';
import { Grid, Row } from 'react-bootstrap';
import ImageWrapper from './ImageWrapper';
import interior1 from '../images/interiors/home_interior1.JPG';
import interior2 from '../images/interiors/home_interior2.JPG';
import interior4 from '../images/interiors/interiors4.jpg';
import interior5 from '../images/interiors/interiors5.jpg';
import interior6 from '../images/interiors/interiors6.jpg';
import interior9 from '../images/interiors/interiors9.jpg';
import interior18 from '../images/interiors/interiors18.jpg';
import interior20 from '../images/interiors/interiors20.jpg';
import deliver from '../images/interiors/deliver_items.jpg';
import lantern4 from '../images/interiors/lantern4.jpg';
import lantern5 from '../images/interiors/lantern5.jpg';
import lantern6 from '../images/interiors/lantern6.jpg';
import lantern8 from '../images/interiors/lantern8.JPG';
import milk_can from '../images/interiors/milk_can.jpg';
import tins from '../images/interiors/tins.JPG';
import tins2 from '../images/interiors/tins2.jpg';
import vase from '../images/interiors/vase.jpg';
import wall_hanging from '../images/interiors/wall_hanging.JPG';
import candle_holders from '../images/interiors/candle_holders.jpg';
import door from '../images/interiors/door.JPG';
import frame from '../images/interiors/frame.jpg';
import clock from '../images/interiors/black and silver clock.JPG';
import heart from '../images/interiors/Key my heart.JPG';
import tray from '../images/interiors/live simply tray.JPG';
import metal_clock from '../images/interiors/metal clock.JPG';
import canister from '../images/interiors/Tin canister.JPG';
import wine_sign from '../images/interiors/wine is awesome sign.JPG';
import wood_and_metal_sign from '../images/interiors/wood and metal sign.JPG';
import wine_bottles from '../images/interiors/Wine_bottles.jpg';
import Bacon_Sign from '../images/interiors/Bacon_Sign.jpg';
import Cabinet from '../images/interiors/Cabinet.jpg';
import Cabinet2 from '../images/interiors/Cabinet(2).jpg';
import Clock2 from '../images/interiors/Clock2.jpg';
import CuttingBoard1 from '../images/interiors/CuttingBoard1.jpg';
import cuttingboard3 from '../images/interiors/cuttingboard3.jpg';
import CuttingBoard5 from '../images/interiors/Cuttingboard5.jpg';
import Doorknobsign from '../images/interiors/Doorknobsign.jpg';
import EdisonLantern from '../images/interiors/EdisonLantern(1).jpg';
import EndTableDecor from '../images/interiors/EndTableDecor(1).jpg';
import endtabledecor2 from '../images/interiors/endtabledecor2.jpg';
import HangingLantern from '../images/interiors/HangingLantern.jpg';
import HangingLight from '../images/interiors/HangingLight.jpg';
import HangingRack from '../images/interiors/HangingRack(1).jpg';
import Mirror from '../images/interiors/Mirror.jpg';
import Mirror2 from '../images/interiors/Mirror2.jpg';
import PillowandDecanter from '../images/interiors/PillowandDecanter.jpg';
import Rooster from '../images/interiors/Rooster1.jpg';
import Winemakingmeawesome from '../images/interiors/Winemakingmeawesome.jpg';
import WoodenTray from '../images/interiors/WoodenTray(1).jpg';
import CabinetLantern from '../images/gifts/HangingLantern.jpg';
import wine_pillows from '../images/interiors/Wine_pillows.jpg';
import Mirrors from '../images/interiors/mirrors.jpeg';
import Lanterns from '../images/interiors/lanterns.jpeg';
import WhiteLamp from '../images/interiors/WhiteLamp.jpeg';
import BlackLamp from '../images/interiors/BlackLamp.jpeg';
import Follow from '../images/interiors/Follow.jpeg';
import Lanterny from '../images/interiors/Lanterny.jpeg';
import GlassLamp from '../images/interiors/GlassLamp.jpeg';
import Clockworth from '../images/interiors/Clockworth.jpg';
import Crusty from '../images/interiors/Crusty.jpg';
import Blackshade from '../images/gifts/Blackshade.jpg';
import crochet from '../images/interiors/crochet.jpg';
import heartstone from '../images/interiors/heartstone.jpg';
import morelights from '../images/interiors/morelights.jpg';
import ropeholes from '../images/interiors/ropeholes.jpg';
import ropeshelf from '../images/interiors/ropeshelf.jpg';
import smalllight from '../images/interiors/smalllight.jpg';
import stuff from '../images/interiors/stuff.jpg';
import art from '../images/interiors/art.jpg';
import biglight from '../images/interiors/biglight.jpg';
import bowbox from '../images/interiors/bowbox.jpg';
import crochetballs from '../images/interiors/crochetballs.jpg';
import crochetbasket from '../images/interiors/crochetbasket.jpg';
import crochetstuff from '../images/interiors/crochetstuff.jpg';
import glassstuff from '../images/interiors/glassstuff.jpg';
import lakestuff from '../images/interiors/lakestuff.jpg';
import lightstuff from '../images/interiors/lightstuff.jpg';
import shotglass from '../images/interiors/shotglass.jpg';
import watercans from '../images/interiors/watercans.jpg';
import ballcage from '../images/interiors/ballcage.jpg';
import clocksome from '../images/interiors/clocksome.jpg';
import fakeplant from '../images/interiors/fakeplant.jpg';
import jugowater from '../images/interiors/jugowater.jpg';
import open from '../images/interiors/open.jpg';
import plantsfake from '../images/interiors/plantsfake.jpg';
import quack from '../images/interiors/quack.jpg';
import someclock from '../images/interiors/someclock.jpg';
import tweety from '../images/interiors/tweety.jpg';
import waterjug from '../images/interiors/waterjug.jpg';
import flowerbasket from '../images/interiors/flowerbasket.jpg';
import faucet from '../images/interiors/faucet.jpg';
import flowerbox from '../images/interiors/flowerbox.jpg';
import flowerpot from '../images/interiors/flowerpot.jpg';
import mirrorcorner from '../images/interiors/mirrorcorner.jpg';
import shortcan from '../images/interiors/shortcan.jpg';
import barrellid from '../images/interiors/barrellid.jpg';
import greenflower from '../images/interiors/greenflower.jpg';
import strawberry from '../images/interiors/strawberry.jpg';
import winedispenser from '../images/interiors/winedispenser.jpg';
import metalflower from '../images/interiors/winedispenser.jpg';
import prix from '../images/interiors/prix.jpg';
import wallcan from '../images/interiors/wallcan.jpg';
import canwall from '../images/interiors/canwall.jpg';
import woodenbox from '../images/interiors/woodenbox.jpg';
import gives from '../images/interiors/gives.jpg';
import greenmirror from '../images/interiors/greenmirror.jpg';
import jellywall from '../images/interiors/jellywall.jpg';
import jellycart from '../images/interiors/jellycart.jpg';
import shoreshells from '../images/interiors/shoreshells.jpg';
import birdcage from '../images/interiors/birdcage.jpg';
import vasebox from '../images/interiors/vasebox.jpg';
import gold from '../images/interiors/gold.jpg';
import Rhombus from '../images/home/Rhombus.jpg';
import Cow from '../images/interiors/Cow.jpg';
import Spade from '../images/interiors/Spade.jpg';
import Cowsetting from '../images/interiors/Cowsetting.jpg';
import Boathook from '../images/interiors/Boathook.jpg';
import Asparagus from '../images/interiors/Asparagus.jpg';
import Dumping from '../images/interiors/Dumping.jpg';
import Followdream from '../images/interiors/Dumping.jpg';
import Peas from '../images/interiors/Peas.jpg';
import Augustlantern from '../images/interiors/Augustlantern.jpg';
import Falllantern from '../images/interiors/Falllantern.jpg';
import Island from '../images/interiors/Island.jpg';
import Islander from '../images/interiors/Islander.jpg';
import i from '../images/interiors/i.jpeg';
import inner from '../images/interiors/inner.jpeg';
import easter1 from '../images/seasonal/easter1.jpeg';
import easter2 from '../images/seasonal/easter2.jpg';
import easter3 from '../images/seasonal/easter3.jpg';
import l from '../images/interiors/l.jpg';
import ll from '../images/interiors/ll.jpg';
import lll from '../images/interiors/lll.jpg';
import k from '../images/interiors/k.jpg';
import kk from '../images/interiors/kk.jpg';
import kkk from '../images/interiors/kkk.jpg';
import kkkk from '../images/interiors/kkkk.jpg';
import kkkkk from '../images/interiors/kkkkk.jpg';
import kkkkkk from '../images/interiors/kkkkkk.jpg';
import pppp from '../images/interiors/pppp.jpg';
import pi from '../images/interiors/i.jpg';
import ii from '../images/interiors/ii.jpg';
import llll from '../images/interiors/llll.jpg';
import lllll from '../images/interiors/lllll.jpg';
import llllll from '../images/interiors/llllll.jpg';
import p from '../images/interiors/p.jpg';
import pp from '../images/interiors/pp.jpg';
import ppp from '../images/interiors/ppp.jpg';
import ppppp from '../images/interiors/ppppp.jpg';
import iii from '../images/interiors/iii.jpg';
import iiii from '../images/interiors/iiii.jpg';
import gi from '../images/gifts/gi.jpg';
import igs from '../images/gifts/igs.jpg';
import i1 from '../images/interiors/i1.jpg';
import i2 from '../images/interiors/i2.jpg';
import i3 from '../images/interiors/i3.jpg';
import i4 from '../images/interiors/i4.jpg';
import i5 from '../images/interiors/i5.jpg';
import i6 from '../images/interiors/i6.jpg';
import i7 from '../images/interiors/i7.jpg';
import i8 from '../images/interiors/i8.jpg';
import i9 from '../images/interiors/i9.jpg';
import i10 from '../images/interiors/i10.jpg';
import i11 from '../images/interiors/i11.jpg';
import i12 from '../images/interiors/i12.jpg';
import i13 from '../images/interiors/i13.jpg';
import i14 from '../images/interiors/i14.jpg';
import i15 from '../images/interiors/i15.jpg';
import i16 from '../images/interiors/i16.jpg';
import i17 from '../images/interiors/i17.jpg';
import i18 from '../images/interiors/i18.jpg';
import i19 from '../images/interiors/i19.jpg';
import t1 from '../images/interiors/t1.jpg';
import t2 from '../images/interiors/t2.jpg';
import t3 from '../images/interiors/t3.jpg';
import t4 from '../images/interiors/t4.jpg';
import t5 from '../images/interiors/t5.jpg';
import t6 from '../images/interiors/t6.jpg';
import t7 from '../images/interiors/t7.jpg';
import t8 from '../images/interiors/t8.jpg';
import t9 from '../images/interiors/t9.jpg';
import t10 from '../images/interiors/t10.jpg';
import t11 from '../images/interiors/t11.jpg';
import carint0 from '../images/interiors/carint0.jpg';
import carint03 from '../images/interiors/carint03.jpg';
import carint9 from '../images/interiors/carint9.jpg';
import carint21 from '../images/interiors/carint21.jpg';
import carint6 from '../images/interiors/carint6.jpg';
import carint23 from '../images/interiors/carint23.jpg';
import carint323 from '../images/interiors/carint323.jpg';
import carint890 from '../images/interiors/carint890.jpg';
import giftsint68 from '../images/interiors/giftsint68.jpg';
import giftsint69 from '../images/interiors/giftsint69.jpg';
import i1h from '../images/interiors/i1h.jpg';
import i3h from '../images/interiors/i3h.jpg';
import i12h from '../images/interiors/i12h.jpg';
import i13h from '../images/interiors/i13h.jpg';
import i14h from '../images/interiors/i14h.jpg';
import i15h from '../images/interiors/i15h.jpg';
import i16h from '../images/interiors/i16h.jpg';
import i1v from '../images/interiors/i1v.jpg';
import i2v from '../images/interiors/i2v.jpg';
import i3v from '../images/interiors/i3v.jpg';
import i4v from '../images/interiors/i4v.jpg';
import i5v from '../images/interiors/i5v.jpg';
import i6v from '../images/interiors/i6v.jpg';
import i7v from '../images/interiors/i7v.jpg';
import i8v from '../images/interiors/i8v.jpg';
import i9v from '../images/interiors/i9v.jpg';
import i10v from '../images/interiors/i10v.jpg';
import i11v from '../images/interiors/i11v.jpg';
import i12v from '../images/interiors/i12v.jpg';
import i20v from '../images/interiors/i20v.jpg';
import i21v from '../images/interiors/i21v.jpg';
import ig1v from '../images/interiors/ig1v.jpg';
import ig2v from '../images/interiors/ig2v.jpg';
import i22v from '../images/interiors/i22v.jpg';
import i23v from '../images/interiors/i23v.jpg';
import i24v from '../images/interiors/i24v.jpg';
import i25h from '../images/interiors/i25h.jpg';
import ig3v from '../images/interiors/ig3v.jpg';
import ig4v from '../images/interiors/ig4v.jpg';
import i26 from '../images/interiors/i26.jpg';
import i27 from '../images/interiors/i27.jpg';
import i28 from '../images/interiors/i28.jpg';
import i29 from '../images/interiors/i29.jpg';
import i30 from '../images/interiors/i30.jpg';
import i31 from '../images/interiors/i31.jpg';
import i32 from '../images/interiors/i32.jpg';
import i34 from '../images/interiors/i34.jpg';
import i35 from '../images/interiors/i35.jpg';
import i36 from '../images/interiors/i36.jpg';
import i37 from '../images/interiors/i37.jpg';
import i38 from '../images/interiors/i38.jpg';
import i39 from '../images/interiors/i39.jpg';
import i40 from '../images/interiors/i40.jpg';
import i41 from '../images/interiors/i41.jpg';
import i42 from '../images/interiors/i42.jpg';
import i43 from '../images/interiors/i43.jpg';
import i44 from '../images/interiors/i44.jpg';
import i45 from '../images/interiors/i45.jpg';
import i46 from '../images/interiors/i46.jpg';
import ig5h from '../images/interiors/ig5h.jpg';


class Interiors extends Component {
  render() {
    return (
      <div>
        <Helmet>
          <meta name="description" content="Simply You Interiors Gifts paola Gift ideas paola Gift baskets paola Clocks paola Custom gifts Personalized gifts paola Paola Panther gifts Paola High school gifts Paola Middle school gifts Christmas gifts paola Mothers day gifts Fathers day gifts paola Birthday gifts paola Shop local paola Gift cards paola Candles paola Picture frames Lamps Lanterns Interior design Kathy Kane Simply You Paola Park Square Lighting Edison bulbs Teenage rooms" />
          <meta name="robots" content="index,follow" />
          <title>Interiors</title>
        </Helmet>
        <div className="title-border">
        <h2 className="p-centered">Simply You Interiors</h2>
        <p className="p-centered">Simply You is situated on the historic park square in Paola. We get new items in weekly so you are sure to find something unique and different each time you visit. Our home interiors collection includes items for each room in your home. We carry items that are timeless as well as some of the latest trends. Check out our new items for Summer!</p>
        </div>
        <Grid className="container-fluid">
          <Row>

            <ImageWrapper image={i37} description={"Interiors"} />
            <ImageWrapper image={i38} description={"Interiors"} />
            <ImageWrapper image={i39} description={"Interiors"} />
            <ImageWrapper image={i40} description={"Interiors"} />
            <ImageWrapper image={i41} description={"Interiors"} />
            <ImageWrapper image={i42} description={"Interiors"} />
            <ImageWrapper image={i43} description={"Interiors"} />
            <ImageWrapper image={i44} description={"Interiors"} />
            <ImageWrapper image={i45} description={"Interiors"} />
            <ImageWrapper image={i46} description={"Interiors"} />
            <ImageWrapper image={ig3v} description={"Interiors"} />
            <ImageWrapper image={ig4v} description={"Interiors"} />
            <ImageWrapper image={i22v} description={"Interiors"} />
            <ImageWrapper image={i23v} description={"Interiors"} />
            <ImageWrapper image={i24v} description={"Interiors"} />
            <ImageWrapper image={i21v} description={"Interiors"} />
            <ImageWrapper image={ig1v} description={"Interiors"} />
            <ImageWrapper image={ig2v} description={"Interiors"} />
            <ImageWrapper image={i1v} description={"Interiors"} />
            <ImageWrapper image={i2v} description={"Interiors"} />
            <ImageWrapper image={i3v} description={"Interiors"} />
            <ImageWrapper image={i4v} description={"Interiors"} />
            <ImageWrapper image={i5v} description={"Interiors"} />
            <ImageWrapper image={i6v} description={"Interiors"} />
            <ImageWrapper image={i7v} description={"Interiors"} />
            <ImageWrapper image={i8v} description={"Interiors"} />
            <ImageWrapper image={i9v} description={"Interiors"} />
            <ImageWrapper image={i10v} description={"Interiors"} />
            <ImageWrapper image={i11v} description={"Interiors"} />
            <ImageWrapper image={i12v} description={"Interiors"} />
            <ImageWrapper image={carint6} description={"Interiors"} />
            <ImageWrapper image={carint23} description={"Interiors"} />
            <ImageWrapper image={carint890} description={"Interiors"} />
            <ImageWrapper image={carint323} description={"Interiors"} />
            <ImageWrapper image={t1} description={"Interiors"} />
            <ImageWrapper image={t3} description={"Interiors"} />
            <ImageWrapper image={t4} description={"Interiors"} />
            <ImageWrapper image={t5} description={"Interiors"} />
            <ImageWrapper image={t6} description={"Interiors"} />
            <ImageWrapper image={t7} description={"Interiors"} />
            <ImageWrapper image={t8} description={"Interiors"} />
            <ImageWrapper image={t9} description={"Interiors"} />
            <ImageWrapper image={t11} description={"Interiors"} />
            <ImageWrapper image={iii} description={"Interiors"} />
            <ImageWrapper image={gi} description={"Interiors"} />
            <ImageWrapper image={Peas} description={"Interiors"} />
            <ImageWrapper image={p} description={"Interiors"} />
            <ImageWrapper image={pp} description={"Interiors"} />
            <ImageWrapper image={ppppp} description={"Interiors"} />
            <ImageWrapper image={llll} description={"Interiors"} />
            <ImageWrapper image={lllll} description={"Interiors"} />
            <ImageWrapper image={llllll} description={"Interiors"} />
            <ImageWrapper image={l} description={"Interiors"} />
            <ImageWrapper image={easter3} description={"Interiors"} />
            <ImageWrapper image={plantsfake} description={"Interiors"} />
            <ImageWrapper image={birdcage} description={"Interiors"} />
            <ImageWrapper image={vasebox} description={"Interiors"} />
            <ImageWrapper image={prix} description={"Interiors"} />
            <ImageWrapper image={gives} description={"Interiors"} />
            <ImageWrapper image={greenmirror} description={"Interiors"} />
            <ImageWrapper image={flowerbasket} description={"Interiors"} />
            <ImageWrapper image={ballcage} description={"Interiors"} />
            <ImageWrapper image={quack} description={"Interiors"} />
            <ImageWrapper image={open} description={"Interiors"} />
            <ImageWrapper image={shoreshells} description={"Interiors"} />
            <ImageWrapper image={tweety} description={"Interiors"} />
            <ImageWrapper image={heartstone} description={"Interiors"} />
            <ImageWrapper image={crochet} description={"Interiors"} />
            <ImageWrapper image={morelights} description={"Interiors"} />
            <ImageWrapper image={ropeholes} description={"Interiors"} />
            <ImageWrapper image={smalllight} description={"Interiors"} />
            <ImageWrapper image={stuff} description={"Interiors"} />
            <ImageWrapper image={Crusty} description={"Interiors"} />
            <ImageWrapper image={Lanterny} description={"Interiors"} />
            <ImageWrapper image={Lanterns} description={"Interiors"} />
            <ImageWrapper image={interior5} description={"Interiors"} />
            <ImageWrapper image={lll} description={"Interiors"} />
            <ImageWrapper image={k} description={"Interiors"} />
            <ImageWrapper image={kk} description={"Interiors"} />
            <ImageWrapper image={kkk} description={"Interiors"} />
            <ImageWrapper image={kkkkk} description={"Interiors"} />
            <ImageWrapper image={kkkkkk} description={"Interiors"} />
            <ImageWrapper image={pi} description={"Interiors"} />
            <ImageWrapper image={ii} description={"Interiors"} />
            <ImageWrapper image={pppp} description={"Interiors"} />
            <ImageWrapper image={gold} description={"Interiors"} />
            <ImageWrapper image={mirrorcorner} description={"Interiors"} />
            <ImageWrapper image={lightstuff} description={"Interiors"} />
            <ImageWrapper image={watercans} description={"Interiors"} />
            <ImageWrapper image={shotglass} description={"Interiors"} />
            <ImageWrapper image={i7} description={"Interiors"} />
            <ImageWrapper image={i8} description={"Interiors"} />
            <ImageWrapper image={i9} description={"Interiors"} />
            <ImageWrapper image={i13} description={"Interiors"} />
            <ImageWrapper image={i14} description={"Interiors"} />
            <ImageWrapper image={i15} description={"Interiors"} />
            <ImageWrapper image={i16} description={"Interiors"} />
            <ImageWrapper image={i17} description={"Interiors"} />
            <ImageWrapper image={i18} description={"Interiors"} />
            <ImageWrapper image={carint0} description={"Interiors"} />
            <ImageWrapper image={carint03} description={"Interiors"} />
            <ImageWrapper image={carint9} description={"Interiors"} />
            <ImageWrapper image={carint21} description={"Interiors"} />
            <ImageWrapper image={giftsint68} description={"Interiors"} />
            <ImageWrapper image={giftsint69} description={"Interiors"} />
            <ImageWrapper image={i1h} description={"Interiors"} />
            <ImageWrapper image={i3h} description={"Interiors"} />
            <ImageWrapper image={i12h} description={"Interiors"} />
            <ImageWrapper image={i13h} description={"Interiors"} />
            <ImageWrapper image={i14h} description={"Interiors"} />
            <ImageWrapper image={i15h} description={"Interiors"} />
            <ImageWrapper image={i16h} description={"Interiors"} />
            <ImageWrapper image={i25h} description={"Interiors"} />
            <ImageWrapper image={i26} description={"Interiors"} />
            <ImageWrapper image={i27} description={"Interiors"} />
            <ImageWrapper image={i28} description={"Interiors"} />
            <ImageWrapper image={i29} description={"Interiors"} />
            <ImageWrapper image={i31} description={"Interiors"} />
            <ImageWrapper image={i30} description={"Interiors"} />
            <ImageWrapper image={i32} description={"Interiors"} />
            <ImageWrapper image={i34} description={"Interiors"} />
            <ImageWrapper image={i35} description={"Interiors"} />
            <ImageWrapper image={i36} description={"Interiors"} />
            <ImageWrapper image={ig5h} description={"Interiors"} />
          </Row>
        </Grid>
      </div>
  );
  }
}

export default Interiors;
